# Generated by Django 2.2.7 on 2019-11-18 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('sdk', models.CharField(max_length=200)),
                ('channel_name', models.CharField(max_length=200)),
                ('desc_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='versionCfg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_text', models.CharField(max_length=200)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushNoticeFile.game')),
            ],
        ),
        migrations.CreateModel(
            name='noticeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='notice date')),
                ('notice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushNoticeFile.notice')),
            ],
        ),
        migrations.CreateModel(
            name='noticeCfg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_text', models.CharField(max_length=200)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushNoticeFile.game')),
            ],
        ),
        migrations.CreateModel(
            name='noticeBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushNoticeFile.game')),
                ('notice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushNoticeFile.notice')),
            ],
        ),
    ]
