# Generated by Django 2.2.7 on 2019-11-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pushNoticeFile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='games',
            field=models.ManyToManyField(to='pushNoticeFile.Game'),
        ),
        migrations.AlterField(
            model_name='noticebatch',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushNoticeFile.Game'),
        ),
        migrations.AlterField(
            model_name='noticebatch',
            name='notice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushNoticeFile.Notice'),
        ),
        migrations.AlterField(
            model_name='noticecfg',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushNoticeFile.Game'),
        ),
        migrations.AlterField(
            model_name='noticelog',
            name='notice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushNoticeFile.Notice'),
        ),
        migrations.AlterField(
            model_name='versioncfg',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushNoticeFile.Game'),
        ),
    ]
