# Generated by Django 2.2.7 on 2019-11-20 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pushNoticeFile', '0002_auto_20191118_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date publiced')),
            ],
        ),
        migrations.RemoveField(
            model_name='notice',
            name='games',
        ),
        migrations.RemoveField(
            model_name='noticebatch',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='noticebatch',
            name='notice_id',
        ),
        migrations.RemoveField(
            model_name='noticecfg',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='noticelog',
            name='notice_id',
        ),
        migrations.RemoveField(
            model_name='versioncfg',
            name='game_id',
        ),
        migrations.DeleteModel(
            name='game',
        ),
        migrations.DeleteModel(
            name='notice',
        ),
        migrations.DeleteModel(
            name='noticeBatch',
        ),
        migrations.DeleteModel(
            name='noticeCfg',
        ),
        migrations.DeleteModel(
            name='noticeLog',
        ),
        migrations.DeleteModel(
            name='versionCfg',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushNoticeFile.Question'),
        ),
    ]
