# Generated by Django 2.2.7 on 2019-11-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pushNoticeFile', '0003_auto_20191120_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=30)),
                ('sdk', models.CharField(max_length=50)),
                ('desc_text', models.CharField(max_length=200)),
                ('version_url', models.CharField(max_length=200)),
                ('notice_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeCfg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_text', models.CharField(max_length=200)),
                ('game', models.ManyToManyField(to='pushNoticeFile.Game')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=4096)),
                ('date', models.DateTimeField(verbose_name='notice Time')),
                ('notice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pushNoticeFile.NoticeCfg')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
