# Generated by Django 2.2.7 on 2019-11-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pushNoticeFile', '0004_auto_20191125_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticelog',
            old_name='notice_id',
            new_name='noticeCfg',
        ),
    ]
