# Generated by Django 2.2.7 on 2019-11-25 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pushNoticeFile', '0005_auto_20191125_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticecfg',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='noticeCfg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pushNoticeFile.NoticeCfg'),
        ),
    ]
