# Generated by Django 2.2.7 on 2019-11-26 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pushNoticeFile', '0006_auto_20191125_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdnCfg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_id', models.CharField(max_length=80)),
                ('secret_key', models.CharField(max_length=80)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SshCfg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('psw', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=20)),
                ('port', models.IntegerField()),
                ('desc_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='cdn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pushNoticeFile.CdnCfg'),
        ),
        migrations.AddField(
            model_name='game',
            name='ssh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pushNoticeFile.SshCfg'),
        ),
    ]
