# Generated by Django 2.2.7 on 2019-11-26 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pushNoticeFile', '0007_auto_20191126_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdncfg',
            old_name='desc',
            new_name='desc_text',
        ),
    ]
