# Generated by Django 2.2.7 on 2019-11-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushNoticeFile', '0008_auto_20191126_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticecfg',
            name='host_url',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='noticecfg',
            name='server_root',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
