# Generated by Django 2.2.7 on 2019-11-27 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pushNoticeFile', '0010_auto_20191127_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cdn',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ssh',
        ),
        migrations.AddField(
            model_name='noticecfg',
            name='cdn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pushNoticeFile.CdnCfg'),
        ),
        migrations.AddField(
            model_name='noticecfg',
            name='ssh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pushNoticeFile.SshCfg'),
        ),
    ]
