// EventUtil.h :
#ifndef __EVENT_UTIL__
#define __EVENT_UTIL__
//
////事件集合定义
//enum EventGroup
//{
//	EVENT_FRAME_SETS = 1000,
//	EVENT_LOGIN_SETS = 2000,
//};
//
//enum FrameEvents
//{
//	FRAME_CS_PLAYER_LOADED = EVENT_FRAME_SETS,	//客户端请求加载玩家到场景
//	FRAME_CS_PLAYER_EXIT,						//客户端请求玩家退出游戏场景
//	FRAME_CG_HEART_BEAT,						//客户端定时发送的心跳包
//	FRAME_SC_MESSAGE,							//服务器发给客户端的提示信息
//	FRAME_CS_MOVE_TO,							//客户端发送给服务器的移动信息
//};
//
//enum LoginEvents
//{
//	LOGIN_CS_SESSION = EVENT_LOGIN_SETS,		
//	LOGIN_SC_SESSION,
//	LOGIN_SC_WORLDUPDATE,
//	LOGIN_CS_CHOOSEWORLD,
//	LOGIN_CS_CREATEUSER,
//	LOGIN_SC_CREATEUSER,
//	LOGIN_CS_CREATEPLAYER,
//	LOGIN_SC_CREATEPLAYER,
//	LOGIN_CS_CHECKPLAYER,
//	LOGIN_SC_CHECKPLAYER,
//	LOGIN_CS_PRE_DELETE,
//	LOGIN_SC_PRE_DELETE,
//	LOGIN_CS_RESUME_PLAYER,
//	LOGIN_SC_RESUME_PLAYER,
//	LOGIN_CS_DELETE_PLAYER,
//	LOGIN_SC_DELETE_PLAYER,
//	LOGIN_SC_GATEWAY_INFO,
//	LOGIN_CG_LOAD_PLAYER,
//	LOGIN_CG_UNLOAD_PLAYER,
//	LOGIN_SG_VERIFY_CODE,
//	LOGIN_GC_VERIFY_CODE,
//	LOGIN_GW_OFFLINE,
//	LOGIN_GW_ENTER_WORLD,
//	LOGIN_GW_QUIT_WORLD,
//	LOGIN_GW_HEART_BEAT,
//	LOGIN_SG_LOGINRESULT,
//	LOGIN_GS_GATEWAY_INFO,
//	LOGIN_GS_PLAYER_INFO,
//	LOGIN_SC_TICKOUT,
//	LOGIN_CG_EXIT2HUD,		// 小退请求
//	LOGIN_CG_SWITCH_LINE,	//换线请求
//};

#endif
